version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - GOOGLE_CLOUD_API_KEY=AQ.Ab8RN6IoSI-lsd44aDisvbWdBXNphqy6NLQhAS-kyDn10ZhnXw
